all:
  hosts:
    local:
      ansible_host: localhost
    raspi:
      ansible_host: localhost
      ansible_port: 2222
      ansible_ssh_user: root
      # Options to skip host verification
      # We don't want to save the finger print as the VM will be getting created afresh each time
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
